// Package docs Code generated by swaggo/swag. DO NOT EDIT
package docs

import "github.com/swaggo/swag"

const docTemplate = `{
    "schemes": {{ marshal .Schemes }},
    "swagger": "2.0",
    "info": {
        "description": "{{escape .Description}}",
        "title": "{{.Title}}",
        "termsOfService": "http://swagger.io/terms/",
        "contact": {
            "name": "API Support",
            "email": "support@woohalabs.com"
        },
        "license": {
            "name": "Apache 2.0",
            "url": "http://www.apache.org/licenses/LICENSE-2.0.html"
        },
        "version": "{{.Version}}"
    },
    "host": "{{.Host}}",
    "basePath": "{{.BasePath}}",
    "paths": {
        "/healthcheck": {
            "get": {
                "description": "서버 및 데이터베이스 상태 상세 확인 (모니터링/디버깅용)",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Health"
                ],
                "summary": "서버 상세 헬스체크",
                "responses": {
                    "200": {
                        "description": "상태 정보 반환 (DB 연결 실패해도 200)",
                        "schema": {
                            "$ref": "#/definitions/handler.HealthResponse"
                        }
                    }
                }
            }
        },
        "/healthcheck/live": {
            "get": {
                "description": "서버가 살아있는지 확인 (DB 연결 무관)",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Health"
                ],
                "summary": "Liveness 체크 (Kubernetes startup/liveness probe용)",
                "responses": {
                    "200": {
                        "description": "서버 정상 가동 중",
                        "schema": {
                            "$ref": "#/definitions/handler.LivenessResponse"
                        }
                    }
                }
            }
        },
        "/healthcheck/ready": {
            "get": {
                "description": "서버가 트래픽을 받을 준비가 됐는지 확인 (DB 연결 포함)",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Health"
                ],
                "summary": "Readiness 체크 (Kubernetes readiness probe용)",
                "responses": {
                    "200": {
                        "description": "트래픽 수신 준비 완료",
                        "schema": {
                            "$ref": "#/definitions/handler.ReadinessResponse"
                        }
                    },
                    "503": {
                        "description": "트래픽 수신 불가 (DB 연결 실패)",
                        "schema": {
                            "$ref": "#/definitions/handler.ReadinessResponse"
                        }
                    }
                }
            }
        }
    },
    "definitions": {
        "handler.DatabaseStatus": {
            "description": "데이터베이스 연결 상태",
            "type": "object",
            "properties": {
                "connected": {
                    "type": "boolean",
                    "example": true
                },
                "latency_ms": {
                    "type": "integer",
                    "example": 5
                },
                "message": {
                    "type": "string",
                    "example": "Database connection successful"
                }
            }
        },
        "handler.HealthResponse": {
            "description": "서버 헬스체크 응답",
            "type": "object",
            "properties": {
                "database": {
                    "$ref": "#/definitions/handler.DatabaseStatus"
                },
                "service": {
                    "type": "string",
                    "example": "ojeomneo-api"
                },
                "status": {
                    "type": "string",
                    "example": "ok"
                },
                "version": {
                    "type": "string",
                    "example": "1.0.0"
                }
            }
        },
        "handler.LivenessResponse": {
            "description": "Kubernetes liveness/startup probe용 간단한 응답",
            "type": "object",
            "properties": {
                "service": {
                    "type": "string",
                    "example": "ojeomneo-api"
                },
                "status": {
                    "type": "string",
                    "example": "ok"
                }
            }
        },
        "handler.ReadinessResponse": {
            "description": "Kubernetes readiness probe용 응답",
            "type": "object",
            "properties": {
                "database": {
                    "type": "boolean",
                    "example": true
                },
                "ready": {
                    "type": "boolean",
                    "example": true
                },
                "status": {
                    "type": "string",
                    "example": "ok"
                }
            }
        }
    }
}`

// SwaggerInfo holds exported Swagger Info so clients can modify it
var SwaggerInfo = &swag.Spec{
	Version:          "1.0.0",
	Host:             "api.woohalabs.com",
	BasePath:         "/ojeomneo/v1",
	Schemes:          []string{"https", "http"},
	Title:            "Ojeomneo API",
	Description:      "Go Fiber v2 기반 REST API 서버",
	InfoInstanceName: "swagger",
	SwaggerTemplate:  docTemplate,
	LeftDelim:        "{{",
	RightDelim:       "}}",
}

func init() {
	swag.Register(SwaggerInfo.InstanceName(), SwaggerInfo)
}
